### ISSUE TITLE
Salutare, cum il pot verifica daca merge?

### ISSUE THREAD

**Issue by essteffan** [letconex/E-factura#1]
Salut, vroiam sa testez acest repo dar nu merge, adica am dat yarn sa instalez dependentele dar cand dau yarn start sau devStart apare

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `nodemon index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js index.js`

**Comment by letconex** [comment]
În principiu rulează cu node app.js, însă momentan proiectul este în stare alpha, nu este viabil pentru utilizare productivă.
